// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type Shareholder struct {
	ID                int32  `json:"id"`
	Name              string `json:"name"`
	Email             string `json:"email"`
	EmailVerified     bool   `json:"email_verified"`
	Mobile            string `json:"mobile"`
	MobileVerified    bool   `json:"mobile_verified"`
	FolioNumber       string `json:"folio_number"`
	CertificateNumber string `json:"certificate_number"`
	PanNumber         string `json:"pan_number"`
	AgreeTerms        bool   `json:"agree_terms"`
}
